# Generated by Django 2.2.9 on 2020-10-27 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_auto_20201021_1818"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["pub_date"]},
        ),
        migrations.AlterField(
            model_name="group",
            name="slug",
            field=models.SlugField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="posts",
                to="posts.Group",
            ),
        ),
    ]
