# Generated by Django 2.2.9 on 2020-12-03 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0005_auto_20201122_1745"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="group",
            options={},
        ),
        migrations.AlterField(
            model_name="group",
            name="description",
            field=models.TextField(
                help_text="Описание группы", verbose_name="Описание"
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="slug",
            field=models.SlugField(
                help_text="Адрес для страницы с группой",
                max_length=256,
                unique=True,
                verbose_name="Слаг",
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="title",
            field=models.CharField(
                help_text="Название группы",
                max_length=200,
                verbose_name="Заголовок",
            ),
        ),
    ]
