# Generated by Django 3.1.4 on 2020-12-20 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0012_auto_20201219_1740"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="description",
            field=models.CharField(
                help_text="Описание группы",
                max_length=200,
                verbose_name="Описание",
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="slug",
            field=models.SlugField(
                help_text="Адрес для группы. Например: 'novaya-gruppa'",
                max_length=256,
                unique=True,
                verbose_name="Адрес",
            ),
        ),
    ]
