# Generated by Django 3.1.4 on 2020-12-24 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20201220_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/', verbose_name='Добавить фотографию'),
        ),
    ]
